### ISSUE TITLE
Change PHP Short Tag

### ISSUE THREAD

**Issue by Nann** [woodpeckerr/mourning#2]
เปลี่ยน php short tag ตรงบรรทัดที่ 75 ของไฟล์ mourning.php ได้ไหมครับคุณโจ้ ผมกลัวว่าจะมีปัญหาเรื่องนี้

**Comment by jojoee** [comment]
ไม่น่าจะมีปัญหานะครับ
ลองเอาโคด `<h1><?= MRN_PLUGIN_NAME; ?></h1>` ไปรันใน
https://www.piliapp.com/php-syntax-check/
