### ISSUE TITLE
I don't know what the problem is

### ISSUE THREAD

**Issue by Nann** [woodpeckerr/mourning#5]
คุณโจ้ครับ ปัญหานี้เกิดจาอะไรหรอครับ มีเว็บไซต์หนึ่งผมใช้ปลั๊กอินตัวนี้เพิ่มเข้าไปแล้วมี แจ้งเตือน นี้มาครับ

![i don't know what the problem is](https://image.prntscr.com/image/Ad-F3jIbR6St1lh8CEjwrg.png)

**Comment by jojoee** [comment]
ดูไม่น่าจะเกี่ยวกับของเรา เลยนะครับ
อันนี้เหมือนมันเกิดจาก plugin `wp-time-capsule` เลยอะครับ
